# Generated by Django 3.0.7 on 2020-07-12 11:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 12, 11, 46, 1, 753256, tzinfo=utc)),
        ),
    ]
