# Generated by Django 3.0.7 on 2020-11-27 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0002_parent_last_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handler.Student')),
            ],
        ),
    ]
