# Generated by Django 3.0.7 on 2020-06-28 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0002_auto_20200624_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='paid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='to_pay',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(default=datetime.date(2020, 6, 28)),
        ),
    ]
