# Generated by Django 3.0.7 on 2020-07-08 10:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0003_auto_20200629_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='absent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='present',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(default=datetime.date(2020, 7, 8)),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField()),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 7, 8, 10, 9, 57, 100258, tzinfo=utc))),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handler.Student')),
            ],
        ),
    ]
