# Generated by Django 3.0.7 on 2020-11-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0003_correction'),
    ]

    operations = [
        migrations.AddField(
            model_name='correction',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correction',
            name='info',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
