# Generated by Django 3.0.7 on 2021-10-02 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0005_auto_20201127_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_year', models.IntegerField(unique=True)),
                ('selected', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='correction',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='handler.Year'),
        ),
        migrations.AddField(
            model_name='parent',
            name='years',
            field=models.ManyToManyField(to='handler.Year'),
        ),
        migrations.AddField(
            model_name='payment',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='handler.Year'),
        ),
        migrations.AddField(
            model_name='student',
            name='years',
            field=models.ManyToManyField(to='handler.Year'),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='handler.Year'),
        ),
    ]
