# Generated by Django 3.0.7 on 2020-07-12 11:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0006_auto_20200712_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 12, 11, 51, 46, 880838, tzinfo=utc)),
        ),
    ]
