# Generated by Django 3.0.7 on 2021-10-14 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0007_studentyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentyear',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='handler.StudentGroup'),
        ),
    ]
