# Generated by Django 3.0.7 on 2021-10-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0008_studentyear_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_month',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='monthly_payment',
            field=models.FloatField(null=True),
        ),
    ]
