# Generated by Django 3.0.7 on 2020-07-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0010_auto_20200713_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
