# Generated by Django 3.0.7 on 2020-07-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0011_auto_20200713_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(),
        ),
    ]
